### ISSUE TITLE
Remove workaround inserted due to bug in upstream clang

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/opencl-clang#130]
The following hack is not needed, because faulty code was fixed in llvm/llvm-project@6d2b75e0887ee87e247756c4d51733616bb2f356

https://github.com/intel/opencl-clang/blob/98d8c034c7004a0beab3b6998aec12dc7e7c2596/common_clang.cpp#L248-L250

**Comment by lwesiers** [comment]
We could then remove this hack beginning from branch 110 to master.

**Comment by haonanya** [comment]
The fix is not present on 11.x https://github.com/llvm/llvm-project/blob/release/11.x/clang/lib/Frontend/CompilerInvocation.cpp#L3780, I have drafted patches for 12.x and higher.
