### ISSUE TITLE
10.0.0-2 fails to compile against SPIRV-LLVM-Translator 10.0.0

### ISSUE THREAD

**Issue by tgurr** [intel/opencl-clang#148]
SPIRV-LLVM-Translator 10.0.0 is the latest released version which is missing https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/d9063e9b770566646810fc72e3d1ed114c60eb39.

```
[ 95%] Building CXX object CMakeFiles/opencl-clang.dir/common_clang.cpp.o
/usr/bin/x86_64-pc-linux-gnu-c++  -DCOMMON_CLANG_EXPORTS -DLIBCOMMON_CLANG_NAME=\"libopencl-clang.so.10\" -DUSE_PREBUILT_LLVM -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/usr/x86_64-pc-linux-gnu/lib/include -I/usr/x86_64-pc-linux-gnu/lib/llvm/10/include -I/var/tmp/paludis/build/dev-libs-opencl-clang-10.0.0_p2/work/build -I/var/tmp/paludis/build/dev-libs-opencl-clang-10.0.0_p2/work/build/.  -march=native -O2 -pipe -fPIC     -std=gnu++14 -o CMakeFiles/opencl-clang.dir/common_clang.cpp.o -c /var/tmp/paludis/build/dev-libs-opencl-clang-10.0.0_p2/work/opencl-clang-10.0.0-2/common_clang.cpp
/var/tmp/paludis/build/dev-libs-opencl-clang-10.0.0_p2/work/opencl-clang-10.0.0-2/common_clang.cpp: In function 'int Compile(const char*, const char**, unsigned int, const char**, const char*, size_t, const char*, const char*, const char*, Intel::OpenCL::ClangFE::IOCLFEBinaryResult**)':
/var/tmp/paludis/build/dev-libs-opencl-clang-10.0.0_p2/work/opencl-clang-10.0.0-2/common_clang.cpp:340:19: error: 'class SPIRV::TranslatorOpts' has no member named 'setMemToRegEnabled'
  340 |         SPIRVOpts.setMemToRegEnabled(true);
      |                   ^~~~~~~~~~~~~~~~~~

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =dev-libs/opencl-clang-10.0.0_p2:10::hardware --destination installed --replacing =dev-libs/opencl-clang-10.0.0_p1:10::installed --x-of-y 1 of 1:
  * When installing 'dev-libs/opencl-clang-10.0.0_p2:10::hardware' replacing { 'dev-libs/opencl-clang-10.0.0_p1:10::installed' }:
  * When running an ebuild command on 'dev-libs/opencl-clang-10.0.0_p2:10::hardware':
  * Install failed for 'dev-libs/opencl-clang-10.0.0_p2:10::hardware' (paludis::ActionFailedError)

make[2]: Leaving directory '/var/tmp/paludis/build/dev-libs-opencl-clang-10.0.0_p2/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/dev-libs-opencl-clang-10.0.0_p2/work/build'
make[2]: *** [CMakeFiles/opencl-clang.dir/build.make:124: CMakeFiles/opencl-clang.dir/common_clang.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/opencl-clang.dir/all] Error 2
make: *** [Makefile:153: all] Error 2
```

**Comment by boegel** [comment]
@tgurr I'm running into the same problem...

How did you deal with this?

It seems like [`compute-runtime` 20.25.17111](https://github.com/intel/compute-runtime/releases/tag/20.25.17111) was built on top of `opencl-clang` 10.0.0-2 which in turn was built on top of an unreleased version of `SPIRV-LLVM-Translator` (which is 10.0.0 + 10 extra commits, see https://github.com/KhronosGroup/SPIRV-LLVM-Translator/compare/v10.0.0...4d43f68a30a510b4e7607351caab3df8e7426a6b)?

**Comment by tgurr** [comment]
@boegel since there's not a proper new release of SPIRV-LLVM-Translator we're still at opencl-clang 10.0.0-1. I was quite busy so I haven't had time to update our compute-runtime yet, we're currently at 20.23.16988. Does the new compute-runtime fail to compile or on runtime? I've the impression that the versions are just a snapshot of what is current, but _usually_ it works with older ones and/or stable releases however my tests are very limited, I just run clinfo and clpeak to verify basic operation when bumping the packages. The whole situation with relying on git revisions instead of having proper dependencies and checks in the build system is a major pain in the a... and can even be extended to more software like shaderc, glslang, vulkan, ...

**Comment by boegel** [comment]
@tgurr I'm running into issues with both `opencl-clang` 10.0.0-1 and 10.0.0-2 (when I use the right `SPIRV-LLVM-Translator` commit for the latter), which I reported in https://github.com/intel/opencl-clang/issues/156

**Comment by tgurr** [comment]
@boegel I've just bumped our packages for compute-runtime 20.25.17111 and it compiled fine against spirv-llvm-translator 10.0.0 and opencl-clang 10.0.0-1 and also seem to work fine on runtime.

https://git.exherbo.org/hardware.git/tree/packages/dev-util/spirv-llvm-translator/spirv-llvm-translator-10.0.0.exheres-0
https://git.exherbo.org/hardware.git/tree/packages/dev-libs/opencl-clang/opencl-clang-10.0.0_p1.exheres-0
https://git.exherbo.org/hardware.git/tree/packages/dev-libs/intel-gmmlib/intel-gmmlib-20.2.2.exheres-0
https://git.exherbo.org/hardware.git/tree/packages/dev-util/intel-graphics-compiler/intel-graphics-compiler-1.0.4241.exheres-0
https://git.exherbo.org/hardware.git/tree/packages/dev-libs/intel-compute-runtime/intel-compute-runtime-20.25.17111.exheres-0

Maybe you can spot something in our build scripts that will be of any use for you as we also have to apply some workarounds.

**Comment by eero-t** [comment]
This issue is over 2 years old.  I assume it can be closed?

**Comment by tgurr** [comment]
> This issue is over 2 years old. I assume it can be closed?

Fine for me, closing.
