### ISSUE TITLE
LLVM 11 based release?

### ISSUE THREAD

**Issue by ArchangeGabriel** [intel/opencl-clang#204]
Hi there,

Arch Linux packager here. ;) We just added LLVM 11 to our tree and are starting rebuilding all stacks against it. Should we expect an LLVM 11 based release here soon or not? :) No pressure at all, this is just for us to decide whether we want to wait for an eventual new release or whether we will move this stack to a separate LLVM 10 build.

Note: this also depends on https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/786.

Regards,
Bruno/Archange

CC @dbermond.

**Comment by ArchangeGabriel** [comment]
SPIRV-LLVM-Translator now has a [LLVM 11 release](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v11.0.0), so no blocker on that side anymore. ;)

**Comment by Titaniumtown** [comment]
Any updates on this? I'm on gentoo and want to remove llvm/clang 10 in favor of 11, but I can't do so without loosing opencl support :(

**Comment by fzou1** [comment]
Please try ocl-open-110 branch. It works with LLVM 11 and SPIRV-LLVM-Translator 11 branch.
We'll release with LLVM 11 next week.

**Comment by fzou1** [comment]
Please check release with LLVM 11: https://github.com/intel/opencl-clang/releases/tag/v11.0.0
Thanks.

**Comment by ArchangeGabriel** [comment]
Already packaged since you tagged y-day: https://www.archlinux.org/packages/community-staging/x86_64/intel-opencl-clang/

Thanks!
