### ISSUE TITLE
llvm 13 - missing part of update

### ISSUE THREAD

**Issue by 0-wiz-0** [intel/opencl-clang#293]
When the supported version was increased to 13, the default in `CMakeLists.txt` was not bumped.
Please change 12 to 13 in https://github.com/intel/opencl-clang/blob/e0d718e677c1c65236aa1a8b5f8e4a3f3cc24fcb/CMakeLists.txt#L23

Thanks.

**Comment by fzou1** [comment]
Merged PR #298. Closed.
