### ISSUE TITLE
llvm-16 requires C++17

### ISSUE THREAD

**Issue by anbe42** [intel/opencl-clang#421]
but CMakeLists.txt still only wants `CMAKE_CXX_STANDARD 14`, resulting in compilation with `-std=gnu++14` which results in
```.../include/llvm/ADT/bit.h:64:56: error: ‘is_integral_v’ is not a member of ‘std’```

see also https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/75d16c218eb05725887d9fc48a5a488e6d9100e7

**Comment by frantisekz** [comment]
This is trivially fixed by https://github.com/intel/opencl-clang/pull/416 .
