### ISSUE TITLE
shared library lost SOVERSION

### ISSUE THREAD

**Issue by anbe42** [intel/opencl-clang#422]
After switching from `add_llvm_library()` to `add_library()` (commit https://github.com/intel/opencl-clang/commit/743bd15adf8c9955f97dd3b5606cefd7ddccc27d) the shared library lost its SOVERSION, the SONAME is simply the unversioned `libopencl-clang.so` while it previously was `libopencl-clang.so.15`. Not a good idea as you can now mix `libLLVM-##.so.1` with incompatible `libopencl-clang.so`.

If I switch it back to
```
add_llvm_library(${TARGET_NAME} SHARED
    ${TARGET_INCLUDE_FILES}
    ${TARGET_SOURCE_FILES}
    $<TARGET_OBJECTS:cl_headers>

  DEPENDS CClangCompileOptions
  LINK_COMPONENTS
    ${OPENCL_CLANG_LLVM_MODULES}
  LINK_LIBS
    ${OPENCL_CLANG_LINK_LIBS}
)
```
and drop `add_dependencies()` and `target_link_libraries()` below
(with `OPENCL_CLANG_LLVM_MODULES` being `all` in case of `LLVM_LINK_LLVM_DYLIB`, as I (as package maintainer for Debian) only care about linking against the shared libraries from separate LLVM and SPIRV-LLVM-Translator builds, but you could probably set it to the module list used in `target_link_libraries()`, too),
I get again a working build with
 - SONAME `libopencl-clang.so.16`
 - linked against `libLLVM-16.so.1` (#417)
 - install target (#418)

**Comment by anbe42** [comment]
`cmake_policy(SET CMP0057 NEW)` should probably be moved to the top of `CMakeLists.txt` as there is usage of `IN_LIST` both before and after this line ...

**Comment by hewj03** [comment]
address this issue in https://github.com/intel/opencl-clang/pull/439

**Comment by hewj03** [comment]
https://github.com/intel/opencl-clang/pull/439 is merged into ocl-open-160 branch, @frantisekz @anbe42 could you please help to check if this issue is resolved?

**Comment by frantisekz** [comment]
#439 fixes this, thanks!

**Comment by anbe42** [comment]
Works for me in the ocl-open-170 branch.
