### ISSUE TITLE
RFE: please updated for LLVM 18.1.x

### ISSUE THREAD

**Issue by kloczek** [intel/opencl-clang#507]
Currently ..
```console
-- [OPENCL-CLANG] Looking for LLVM version 17.0.1
CMake Error at CMakeLists.txt:52 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "17.0.1".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/llvm/LLVMConfig.cmake, version: 18.1.2
    /lib64/cmake/llvm/LLVMConfig.cmake, version: 18.1.2
```

**Comment by wenju-he** [comment]
@kloczek [ocl-open-180](https://github.com/intel/opencl-clang/compare/ocl-open-180) branch should be now fixed by https://github.com/intel/opencl-clang/commit/b1e321949cf034954e35fc76b7c71e690beeaccf as llvm requires both major and minor versions when finding llvm package since 18.1.0, see https://github.com/llvm/llvm-project/blob/defc4859b032ccaec69f24b6cfd9882fece5f093/llvm/cmake/modules/AddLLVM.cmake#L665

**Comment by kloczek** [comment]
OK I understand however it is already ~3 weeks since 18.1.0 has been released and in mean time has been released another two stable minor releases of the LLVM.
Is it anything on outstanding list? If yes could you please tell what still needs to be done before release stable new version for latest LLVM. I can understand causes like lack of time but my question is more about other (technical) causes 🤔 
Simple it would be good to know ..

**Comment by wenju-he** [comment]
> OK I understand however it is already ~3 weeks since 18.1.0 has been released and in mean time has been released another two stable minor releases of the LLVM. Is it anything on outstanding list? If yes could you please tell what still needs to be done before release stable new version for latest LLVM. I can understand causes like lack of time but my question is more about other (technical) causes 🤔 Simple it would be good to know ..

I've just created a release tag https://github.com/intel/opencl-clang/releases/tag/v18.1.0 that linked against [LLVM 18.1.0](https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.0) and [SPIR-V LLVM translator v18.1.0](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v18.1.0).
Sorry for the delay. There isn't technical cause. It is just that we forgot to prioritize on this. In the future we'll keep pace with the next release of SPIR-V LLVM translator.
