### ISSUE TITLE
Add automated releases for llvm branches

### ISSUE THREAD

**Issue by ZzEeKkAa** [intel/opencl-clang#537]
Hello there!
I see that patches are being backported to to the older llvm branches, but never being released. Is it okay to add automated releases for it? So that different build systems, like conda can references them?

I've done it for spirv-llvm-translator, and it looks like same pattern could be applied to this repository:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2586

**Comment by wenju-he** [comment]
hi @ZzEeKkAa thank you for the suggestion. I think it is a good idea to add automatic release that includes new changes to opencl-clang (although it is not frequent) and link with latest release of llvm and SPIRV-LLVM-Translator.
Do you have bandwidth to work on this?

**Comment by th0ma7** [comment]
I second that!  Would be great to have this.  One note thought is that automated patching using git part of the build process won't work anymore and will need to be adapted.  Ref.: https://github.com/intel/opencl-clang/issues/538
