### ISSUE TITLE
ocl-open-80: please, make release update

### ISSUE THREAD

**Issue by dvrogozh** [intel/opencl-clang#73]
Hi, there are some commits in the head of ocl-open-80 not reflected in v8.0.0-1. Could you, please, make a new release, v8.0.0-2?

**Comment by AlexeySotkin** [comment]
I'd like to have https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/207 merged first.

**Comment by AlexeySotkin** [comment]
BTW, should we target llvm 8.0.**1** ?

**Comment by dvrogozh** [comment]
I believe yes. If new version of llvm-8 is available, we better target it. I suggest to cleanup patches recommendations if needed (rebase and/or drop if not needed anymore).

**Comment by dvrogozh** [comment]
BTW. If there will be new changes in spirv translator, new release for this component is needed as well.

**Comment by dvrogozh** [comment]
@AlexeySotkin : any update?

**Comment by AlexeySotkin** [comment]
8.0.1-1 release was created.
