### ISSUE TITLE
Update spirv translator patch for LLVM-8 (current one fails to apply)

### ISSUE THREAD

**Issue by dvrogozh** [intel/opencl-clang#83]
Noted in https://github.com/intel/compute-runtime/issues/195#issuecomment-517612705

SPIRV translator llvm_release_80 branch was recently updated with a number of patches (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commits/llvm_release_80). As a result opencl-clang suggested custom patch (https://github.com/intel/opencl-clang/blob/ocl-open-80/patches/spirv/0001-Update-LowerOpenCL-pass-to-handle-new-blocks-represn.patch) fails to apply.

It probably makes sense to update custom patch to make it apply clean on the top of spirv translator 80 branch.

Related question is whether spirv translator plans to make release update from 80 branch?

**Comment by AlexeySotkin** [comment]
> Related question is whether spirv translator plans to make release update from 80 branch?

Yes, I think so.
