### ISSUE TITLE
Please make a release against llvm-9

### ISSUE THREAD

**Issue by dvrogozh** [intel/opencl-clang#93]
Depends on https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/334

It seems llvm-9 is finally out. Can you, please, tag a release on your side since this is required for packaging in the distros. For example, Ubuntu 19.10 might wish to go with llvm-9.

**Comment by tjaalton** [comment]
KhronosGroup/SPIRV-LLVM-Translator#334 is fixed now, so it's time to tag a release here

**Comment by dvrogozh** [comment]
Thank you!
